# Generated by Django 4.0.6 on 2022-07-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdversarialAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iter', models.CharField(default='20', max_length=30)),
                ('epsilon', models.CharField(default='0.1', max_length=60)),
                ('attack_method', models.CharField(default='pgd', max_length=70)),
                ('image', models.CharField(default='', max_length=1000000000000000000)),
            ],
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='description',
            field=models.CharField(default='', max_length=1000000000000000000),
        ),
    ]
