# Generated by Django 4.0.6 on 2022-07-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_adversarialattack_alter_tutorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversarialattack',
            name='attack_image',
            field=models.CharField(default='', max_length=1000000000000000000),
        ),
        migrations.AddField(
            model_name='adversarialattack',
            name='perturbation',
            field=models.CharField(default='', max_length=1000000000000000000),
        ),
    ]
