# Generated by Django 4.0.6 on 2022-08-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_adversarialattack_image_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='adversarialattack',
            name='attack_class',
            field=models.CharField(default='candle', max_length=60),
        ),
        migrations.AddField(
            model_name='adversarialattack',
            name='perturbation_class',
            field=models.CharField(default='candle', max_length=60),
        ),
        migrations.AlterField(
            model_name='adversarialattack',
            name='epsilon',
            field=models.CharField(default='0.3', max_length=60),
        ),
        migrations.AlterField(
            model_name='adversarialattack',
            name='iter',
            field=models.CharField(default='40', max_length=30),
        ),
    ]
