# Generated by Django 4.0.6 on 2022-08-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0005_adversarialattack_attack_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackdoorAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_class', models.CharField(default='candle', max_length=60)),
                ('attack_method', models.CharField(default='pgd', max_length=70)),
                ('image', models.CharField(default='', max_length=1000000000000000000)),
                ('perturbation', models.CharField(default='', max_length=1000000000000000000)),
                ('attack_image', models.CharField(default='', max_length=1000000000000000000)),
                ('attack_class', models.CharField(default='4', max_length=60)),
            ],
        ),
    ]
