# Generated by Django 4.0.6 on 2022-08-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_backdoorattack'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextAttack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_class', models.CharField(default='candle', max_length=60)),
                ('attack_method', models.CharField(default='pgd', max_length=70)),
                ('text', models.CharField(default='', max_length=1000000000000000000)),
                ('attack_text', models.CharField(default='', max_length=1000000000000000000)),
                ('attack_class', models.CharField(default='4', max_length=60)),
                ('dataset', models.CharField(default='imdb', max_length=60)),
            ],
        ),
    ]
