# Generated by Django 4.0.6 on 2022-08-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_textattack'),
    ]

    operations = [
        migrations.AddField(
            model_name='textattack',
            name='model',
            field=models.CharField(default='lstm', max_length=60),
        ),
    ]
